name: npm

on: push

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v3.1.0
      - name: Install dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Prettify code
        run: npm run prettier