name: npm

on: push

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v3.1.0
      - name: Print current branch
        run: git rev-parse --abbrev-ref HEAD
      - name: Print current commit hash
        run: git rev-parse --short HEAD