name: npm

on: push

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v3.1.0
      - name: Print node version
        run: node -v
      - name: Upgrade node-sass version
        run: yarn add node-sass
      - name: Install dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Prettify code
        run: npm run prettier
      - name: Run Jest
        run: CI=true npm run test
      - name: Run build
        run: npm run build